// Claude 초벌 채점 — 루브릭 5기준 × 0-2. 사용자 점수와 독립.
// note: 판단 근거 한 줄(의견 갈릴 만한 카드 위주).
window.CLAUDE_SCORES = {
  // ── 1주차 시간축 ──
  'p-1':  { form:2, intent:2, purity:1, link:1, rare:1, note:'대칭+색대비+텍스처 협력. 다만 thesis(시간의 두께)와 분석(얼굴 도식)이 살짝 두 갈래.' },
  'p-1a': { form:2, intent:1, purity:1, link:1, rare:1 },
  'p-1b': { form:1, intent:1, purity:2, link:2, rare:1, note:'[합의 완료 7★] 완성도·자립은 유 판단(발견 하나에 기댐, 완결성 불확실), 순도·연결성은 클 판단(한 문장 완결 + 빛-번역 계열 허브)으로 수렴.' },
  'p-1c': { form:1, intent:1, purity:2, link:1, rare:2, note:'착시 메커니즘을 다룬 유일 카드.' },
  'p-1d': { form:1, intent:1, purity:2, link:1, rare:0, note:'[중간 수렴 확정]' },
  'p-1e': { form:1, intent:1, purity:1, link:1, rare:0 },
  'p-2': { form:1, intent:1, purity:1, link:2, rare:0, note:'[중간 수렴 확정]' },
  'p-2a': { form:1, intent:1, purity:2, link:2, rare:1 },
  'p-2b': { form:1, intent:1, purity:1, link:1, rare:1 },
  'p-2c': { form:1, intent:2, purity:2, link:1, rare:1 },
  'p-2d': { form:1, intent:2, purity:2, link:1, rare:1, note:'"기능과 형태가 하나" — 이멀전씨·그로밋과 좋은-기능-디자인 계열.' },
  'p-2e': { form:2, intent:2, purity:2, link:2, rare:0, note:'질서-속-예외 허브지만 그래서 희소성 0.' },
  'p-3':  { form:2, intent:1, purity:1, link:2, rare:1, note:'[합의 완료 7★] 완성도 2(동심원+크기 리듬+질감 협력). 순도 1 절충 — 아이디어가 다양해 한 문장으로 겨우 묶이는 상태(0도 2도 아닌 정의상 1). 해석-뒤집힘 계열 선구로 연결 2.' },
  'p-3a': { form:2, intent:1, purity:2, link:1, rare:1, note:'[중간 수렴 확정]' },
  'p-3b': { form:2, intent:2, purity:2, link:1, rare:0 },
  // ── 1주차 공간축 ──
  'pg-1':  { form:2, intent:1, purity:2, link:2, rare:1, note:'[합의 완료 8★] 완성도는 유 판단 수용 — 손글씨 기입란은 서식에 설계된 공간이라 활자 위계+기입란이 협력하는 디자인. 일치는 클 판단(카드 핵심은 보존 상태). 연결성 2 — 시간-기록 계열(중3-4앙·슈).' },
  'pg-1a': { form:1, intent:2, purity:2, link:2, rare:0, note:'[합의 완료 7★] 자립 2 — 찍힌 순간 이미 조형이 되었고 우리는 해석할 뿐(유 논거 수용). 완성도 1 — 열린 창이 잘 안 보여 계열의 대표는 아님(유 인정). 희소성 0 — 질서-속-예외 계열 다수.' },
  'pg-1b': { form:1, intent:2, purity:1, link:1, rare:2, note:'직접 보정한 유일한 카드 — 자기 의도 실현이라 일치 2, 편집 의존이라 완성도 1.' },
  'pg-1c': { form:1, intent:1, purity:2, link:1, rare:1 },
  'pg-1d': { form:2, intent:2, purity:2, link:2, rare:0, note:'균질 노랑+보색 하나+그림자 형. "빛에 의해 번역된 결과물" — 빛-번역 계열 허브.' },
  'pg-1e': { form:1, intent:1, purity:1, link:1, rare:1 },
  'pg-2':  { form:1, intent:2, purity:2, link:2, rare:1 },
  'pg-2a': { form:1, intent:1, purity:1, link:1, rare:1 },
  'pg-2b': { form:2, intent:2, purity:1, link:2, rare:0, note:'[중간 수렴 확정]' },
  'pg-2c': { form:1, intent:1, purity:1, link:1, rare:0 },
  'pg-3':  { form:2, intent:2, purity:2, link:2, rare:0, note:'반복+깊이 그라데이션+여백 쉼표 세 원리 협력 — 완성도 2로 봤어요.' },
  'pg-3a': { form:2, intent:2, purity:1, link:1, rare:1 },
  'pg-3b': { form:2, intent:2, purity:2, link:1, rare:0, note:'[합의 완료 7★] 완성도·일치 2 — 화가의 질서와 촬영자의 프레이밍이 만나는 조형적 일치(유 논거 수용). 순도 2 — thesis 단일(거리-위계 통찰은 추후 별도 카드로 분리 예정). 연결성 1 양보(반복+변주 계열).' },
  'pg-3c': { form:2, intent:2, purity:2, link:2, rare:0 },
  'pg-3d': { form:2, intent:2, purity:2, link:1, rare:0, note:'[중간 수렴 확정]' },
  // ── 2주차 ──
  'pw2-1':  { form:1, intent:1, purity:1, link:1, rare:1 },
  'pw2-2':  { form:2, intent:2, purity:2, link:1, rare:1, note:'"사물을 놓는 관습이 자리를 정해둔다" — 순도 2.' },
  'pw2-3':  { form:2, intent:1, purity:2, link:2, rare:1 },
  'pw2-4':  { form:2, intent:2, purity:2, link:1, rare:1 },
  'pw2-5':  { form:2, intent:1, purity:2, link:2, rare:1, note:'"과정의 흔적으로 만들어진 표면" — 서리·녹은 아스팔트와 과정-흔적 계열.' },
  'pw2-6':  { form:2, intent:1, purity:1, link:1, rare:1 },
  'pw2-7':  { form:2, intent:1, purity:2, link:2, rare:1 },
  'pw2-8':  { form:2, intent:1, purity:2, link:2, rare:1 },
  'pw2-9':  { form:2, intent:2, purity:2, link:1, rare:1 },
  'pw2-10': { form:1, intent:1, purity:2, link:2, rare:0, note:'[합의 완료 6◆] 완성도·자립은 유 판단(주제부·시선 명확성 부족, 밤거리에서 눈에 안 띔), 순도는 2로 격상("결손은 기록"), 희소성은 쇠락 계열로 묶어 0.' },
  'pw2-11': { form:2, intent:2, purity:2, link:2, rare:0, note:'"최악의 상태를 미리 그려둔다" — 경고와광고(반례)·픽토그램과 연결 2.' },
  'pw2-12': { form:1, intent:1, purity:2, link:2, rare:0 },
  'pw2-13': { form:2, intent:1, purity:2, link:1, rare:1, note:'[합의 완료 7★] 완성도·순도 2 합의. 자립 1 — 여러 해석의 여지(유 판단). 연결 1.' },
  'pw2-14': { form:2, intent:1, purity:2, link:1, rare:1 },
  'pw2-15': { form:2, intent:2, purity:2, link:2, rare:0 },
  // ── 3주차 ──
  'pw3-1':  { form:1, intent:2, purity:2, link:2, rare:1 },
  'pw3-2':  { form:1, intent:1, purity:2, link:2, rare:1 },
  'pw3-3':  { form:1, intent:2, purity:2, link:2, rare:1, note:'통찰(지각의 작동)은 강하나 조형 자체는 figure/ground+폐합 단순 — 완성도 1. 유 9/클 8.' },
  'pw3-4':  { form:2, intent:2, purity:2, link:2, rare:0 },
  'pw3-5':  { form:2, intent:1, purity:2, link:2, rare:1, note:'형태가 기능을 이긴다는 본인 지적 그대로 일치 1.' },
  'pw3-6':  { form:2, intent:2, purity:2, link:2, rare:1, note:'기능 구조+빛의 번역, "의미가 비어도 외부 조건이 입힌다" — 3주차 대표 각인 후보.' },
  'pw3-7':  { form:1, intent:0, purity:2, link:2, rare:1, note:'의도-조형 어긋남이 주제라 일치 0, 대신 "강조는 덜어냄" 순도 2 — 나쁜 조형의 정석 채점.' },
  'pw3-8':  { form:1, intent:0, purity:2, link:2, rare:0 },
  'pw3-9':  { form:1, intent:0, purity:2, link:2, rare:1 },
  'pw3-10': { form:1, intent:0, purity:2, link:2, rare:1 },
  // ── 4주차 ──
  'pw4-1': { form:2, intent:1, purity:2, link:2, rare:0, note:'[중간 수렴 확정]' },
  'pw4-2':  { form:2, intent:2, purity:2, link:1, rare:1, note:'맘모스 빵 단면과 적층 연결.' },
  'pw4-3':  { form:2, intent:2, purity:2, link:2, rare:0 },
  'pw4-4':  { form:1, intent:1, purity:1, link:1, rare:1 },
  'pw4-5': { form:2, intent:2, purity:1, link:2, rare:0, note:'[중간 수렴 확정]' },
  'pw4-6': { form:2, intent:1, purity:2, link:1, rare:1, note:'[중간 수렴 확정]' },
  'pw4-7':  { form:2, intent:2, purity:2, link:2, rare:0, note:'질서-속-예외 계열의 종착 카드 — 계열이 커서 희소성 0.' },
  'pw4-8':  { form:2, intent:2, purity:2, link:1, rare:1, note:'[합의 완료 8★] 일치 2 — 가게 주인의 의도(밀도로 활기)가 실제 전달됨(유 논거 수용). 연결 1 — 밀도는 군집·색대비 어느 쪽으로도 묶여 단일 계열 아님(유 동의).' },
  'pw4-9':  { form:1, intent:1, purity:2, link:1, rare:2, note:'[합의 완료 7★] 순도 2("고른 면" 한 문장). 희소성 2 — 주인공-없음을 다룬 유일 카드. 자립 1 — 무엇을 찍었는지 헷갈릴 위험(유 판단 수용).' },
  'pw4-10': { form:2, intent:2, purity:2, link:2, rare:0 },
  'pw4-11': { form:2, intent:2, purity:2, link:2, rare:1, note:'분산과 집중의 맞당김 — 유·클 둘 다 9. 합의된 각인.' },
  'pw4-12': { form:2, intent:2, purity:2, link:2, rare:1, note:'[합의 완료 9✦] 순도 2 — 모음 자체가 하나의 아이디어. 연결 2 — 한남과 방치/큐레이션 반대짝 + 올디스 타코. 각인 = 금테(점수 기준, 팩당 제한 없음).' },
  'pw4-20': { form:1, intent:1, purity:2, link:2, rare:1, note:'주의: 이 카드 analysis가 pw3-10(갇혀버린 창) 본문 복붙으로 들어가 있음 — 데이터 수정 필요. 채점은 thesis 기준.' },
  'pw4-21': { form:2, intent:1, purity:2, link:1, rare:1, note:'[중간 수렴 확정]' },
  'pw4-30': { form:2, intent:2, purity:2, link:1, rare:1 },

  // ── 작품 카드(pj) — [클로드 초안] 프레이밍=내 조형 행위 원칙으로 채점. 유저 합의 대기 ──
  'pj-01': { form:2, intent:2, purity:2, link:1, rare:1, note:'[클로드 초안 8★] 노동→패턴→벽. 질감 계열의 허브.' },
  'pj-02': { form:2, intent:2, purity:1, link:1, rare:1, note:'[클로드 초안 7★] 신체 속도가 색 층으로 기록됨.' },
  'pj-03': { form:1, intent:2, purity:1, link:1, rare:2, note:'[클로드 초안 7★] 가지치기가 낳은 우연한 생물 형상.' },
  'pj-04': { form:1, intent:1, purity:2, link:1, rare:1, note:'[클로드 초안 6◆] 규칙으로만 빚은 수평선 — 순도는 높으나 완결은 약함.' },
  'pj-05': { form:1, intent:2, purity:2, link:2, rare:1, note:'[클로드 초안 8★] 은빛 속 살아남은 한 조각 — 질서 속 예외 계열과 강한 연결.' },
  'pj-06': { form:2, intent:2, purity:1, link:2, rare:1, note:'[클로드 초안 8★] 동심원이 몸의 경험(어지럼)까지 끌고 옴 — 동심원 계열.' },
  'pj-07': { form:2, intent:1, purity:1, link:1, rare:1, note:'[클로드 초안 6◆] 질감만으로 분위기를 세움.' },
  'pj-08': { form:2, intent:2, purity:2, link:1, rare:1, note:'[클로드 초안 8★] 같은 금속의 두 질감 대비가 한 문장으로 완결.' },
  'pj-09': { form:2, intent:1, purity:1, link:1, rare:1, note:'[클로드 초안 6◆] 크롬 군무 — 시각적 완성도 대비 통찰이 얕음.' },
  'pj-10': { form:1, intent:2, purity:1, link:0, rare:2, note:'[클로드 초안 6◆] 기억의 박제라는 서사 — 연결 고리는 없음.' },
  'pj-11': { form:2, intent:2, purity:1, link:2, rare:2, note:'[클로드 초안 9✦] 분류 체계가 곧 의미 — 이 카드덱 자체의 자화상. 합체 3분할.' },
  'pj-12': { form:2, intent:2, purity:2, link:1, rare:0, note:'[클로드 초안 7★] 여백·정면·절제 — 교과서적이라 희소성은 0.' },
  'pj-13': { form:1, intent:2, purity:1, link:1, rare:2, note:'[클로드 초안 7★] 접으면 본체가 드러나는 상태형 파사드.' },
  'pj-14': { form:1, intent:2, purity:2, link:1, rare:1, note:'[클로드 초안 7★] 지키던 쓰임이 놓는 쓰임으로 — 쓸모 전환 계열(p-2 낚시).' },
  'pj-15': { form:2, intent:2, purity:2, link:1, rare:1, note:'[클로드 초안 8★] 가로수 실루엣에 맞춘 타이포 — 의도와 조형의 정합.' },
  'pj-16': { form:2, intent:1, purity:1, link:1, rare:1, note:'[클로드 초안 6◆] 수직의 압도를 수평이 끊음.' },
  'pj-17': { form:2, intent:1, purity:1, link:2, rare:0, note:'[클로드 초안 6◆] 격자 반복 vs 개방 층 — 질서 계열 연결.' },
  'pj-18': { form:1, intent:2, purity:1, link:2, rare:1, note:'[클로드 초안 7★] 작품보다 장치에 시선이 가는 어긋남 — 어긋난 해석 계열.' },
  'pj-19': { form:1, intent:1, purity:1, link:1, rare:1, note:'[클로드 초안 5◆] 균질한 백색 공간 — 표지가 읽히지 않는 상태.' },
  'pj-20': { form:1, intent:1, purity:1, link:2, rare:2, note:'[클로드 초안 7★] 파스텔 빛 속 다른 한 마리 — 질서 속 예외 계열.' },
};
